### ISSUE TITLE
how to declare QDateTime-typed field?

### ISSUE THREAD

**Issue by ArcticLampyrid** [AMOSOMNUM/Cpp-JsonDeserialiser#1]

**Comment by AMOSOMNUM** [comment]
QDateTime mtime;
auto f1 = [](const QString& text){return QDateTime::fromString("TIME_FORMAT");};
auto f2 = [](const QDateTime& time){return time.toString("TIME_FORMAT");};
declare_extension_deserialiser("Time", mtime, time_holder, f1, f2);

**Comment by ArcticLampyrid** [comment]
I need to put QDateTime into a struct and deserialize the whole struct, not making QDateTime a top-level thing.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ArcticLampyrid** [comment]
eg. struct ModelA {QDateTime time; QString title;QString location;}

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AMOSOMNUM** [comment]
working on it!

**Comment by AMOSOMNUM** [comment]
auto f1 = [](const QString& text){return QDateTime::fromString(text, "TIME_FORMAT");};
auto f2 = [](const QDateTime& time){return time.toString("TIME_FORMAT");};
declare_global_extension(QDateTime, QString, f1, f2);

Then you can treat this type as a basic type using macro "register_object_member" etc.
